#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CQL
version:      0.1
version_from: lib/CQL/Parser.pm
installdirs:  site
requires:
    String::Tokenizer:             0.05
    Test::Exception:               0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
